x-api-env: &api-env
  - API_DB_HOST=postgres
  - API_DB_PORT=5432
  - API_DB_USERNAME=terra
  - API_DB_PASSWORD=abc123
  - API_DB_DATABASE=api
  - API_DB_SYNCHRONIZE=true
  - FCD_DB_HOST=postgres 
  - FCD_DB_PORT=5432
  - FCD_DB_USERNAME=terra
  - FCD_DB_PASSWORD=abc123
  - FCD_DB_DATABASE=fcd
  - LCD_COLLECTOR_ENDPOINTS=http://terrad:1317
  - RPC_COLLECTOR_ENDPOINTS=http://terrad:26657
  - WS_ENDPOINTS=ws://terrad:26657/websocket
  - MANTLE_ENDPOINTS=
  - FCD_URL=http://fcd-api:3060
  - CIRCULATING_SUPPLY_COLLECT_WINDOW_BLOCKS=10

volumes:
  localterra:
  pgdata:

networks:
  localterra: