version: "3.8"

x-fcd-env: &fcd-env
  - CHAIN_ID=localterra
  - LCD_URI=http://terrad:1317
  - RPC_URI=http://terrad:26657
  - USE_LOG_FILE=true
  - TYPEORM_CONNECTION=postgres
  - TYPEORM_HOST=postgres
  - TYPEORM_USERNAME=terra
  - TYPEORM_PASSWORD=abc123
  - TYPEORM_DATABASE=fcd
  - TYPEORM_SYNCHRONIZE=true
  - TYPEORM_LOGGING=false
  - TYPEORM_ENTITIES=src/orm/*Entity.ts
  - LEGACY_NETWORK=false

services:
  terrad:
    extends:
      file: compose-rpc.yml
      service: terrad

  postgres:
    image: postgres:14-alpine
    hostname: postgres
    environment:
      POSTGRES_USER: terra
      POSTGRES_PASSWORD: abc123
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    networks:
      - default
    ports:
      - 5433:5432

  fcd_collector:
    image: ghcr.io/terra-money/fcd:${TERRA_VERSION}
    command: collector
    hostname: fcd_collector
    restart: unless-stopped
    environment: *fcd-env
    volumes:
      - ./logs:/app/logs
    networks:
      - default

  fcd_api:
    image: ghcr.io/terra-money/fcd:${TERRA_VERSION}
    command: start
    hostname: fcd_api
    environment: *fcd-env
    volumes:
      - ./logs:/app/logs
    networks:
      - default
    ports:
      - 3060:3060

volumes:
  terra:
  pgdata:

networks:
  default:
