version: "3.8"

x-fcd-env: &fcd-env
  - CHAIN_ID=localterra
  - LCD_URI=http://terrad:1317
  - RPC_URI=http://terrad:26657
  - USE_LOG_FILE=true
  - TYPEORM_CONNECTION=postgres
  - TYPEORM_HOST=postgres
  - TYPEORM_USERNAME=terra
  - TYPEORM_PASSWORD=abc123
  - TYPEORM_DATABASE=fcd
  - TYPEORM_SYNCHRONIZE=true
  - TYPEORM_LOGGING=false
  - TYPEORM_ENTITIES=src/orm/*Entity.ts
  - LEGACY_NETWORK=false

services:
  terrad:
    extends:
      file: compose-rpc.yml
      service: terrad

  postgres:
    image: postgres:14-alpine
    container_name: localterra-postgres
    hostname: postgres
    environment:
      POSTGRES_USER: terra
      POSTGRES_PASSWORD: abc123
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    networks:
      - localterra
    ports:
      - 5433:5432

  fcd-collector:
    image: ghcr.io/terra-money/fcd:${TERRA_VERSION}
    container_name: localterra-fcd-collector
    hostname: fcd-collector
    command: collector
    restart: unless-stopped
    environment: *fcd-env
    volumes:
      - ./logs:/app/logs
    networks:
      - localterra

  fcd-api:
    image: ghcr.io/terra-money/fcd:${TERRA_VERSION}
    container_name: localterra-fcd-api
    hostname: fcd-api
    command: start
    environment: *fcd-env
    volumes:
      - ./logs:/app/logs
    networks:
      - localterra
    ports:
      - 3060:3060

volumes:
  localterra:
  pgdata:

networks:
  localterra:
