version: "3"

services:
  terrad:
    image: terracore
    depends_on:
      - redis
    networks:
      - terra
    ports:
      - "26657:26657"
    command: terrad start
  lcd:
    image: terracore
    depends_on:
      - terrad
    networks:
      - terra
    ports:
      - "1317:1317"
    command: terracli rest-server --laddr=tcp://0.0.0.0:1317 --node=tcp://terrad:26657 --trust-node=true
  redis:
    image: redis:latest
    networks:
      - terra
    ports:
      - "6379:6379"

networks:
  terra:
