services:
  terrad:
    extends:
      file: compose-rpc.yml
      service: terrad

  postgres:
    extends:
      file: compose-fcd.yml
      service: postgres

  fcd-collector:
    extends:
      file: compose-fcd.yml
      service: fcd-collector

  fcd-api:
    extends:
      file: compose-fcd.yml
      service: fcd-api

  api-collector:
    extends:
      file: compose-api.yml
      service: fcd-collector

  api:
    extends:
      file: compose-api.yml
      service: fcd-api

volumes:
  terra:
  pgdata:

networks:
  default:
